name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Adaptive Media
author: The Octocat
author_url: https://github.com/octocat
base_url: ''
interpolate: false
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    site_name: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
    source-highlighter: coderay
    coderay-css: style
#    awestruct-layout: base@  # will this work?
disqus: writeadapt
disqus_generate_id: true
disqus_developer: true
