name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Adaptive Media
author: The Octocat
author_url: https://github.com/octocat
base_url: ''
ctx_path: ''
edit_base_url: https://github.com/graphitefriction/writeadapt-graphitefriction/edit/master
raw_base_url: https://github.com/graphitefriction/writeadapt-graphitefriction/raw/master
log_base_url: https://github.com/graphitefriction/writeadapt-graphitefriction/commits/master
interpolate: false
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    site_name: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
    source-highlighter: coderay
    coderay-css: style
#    awestruct-layout: base@  # will this work?
disqus: writeadapt-graphitefriction
disqus_generate_id: true
disqus_developer: true
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://graphitefriction.github.io/writeadapt-graphitefriction
    ctx_path: /writeadapt-graphitefriction
    disqus_developer: false
    asciidoctor:
      :attributes:
        base_url: http://graphitefriction.github.io/writeadapt-graphitefriction
        ctx_path: /writeadapt-graphitefriction
        # necessary to set imagesdir to absolute path to prevent Awestruct from botching Atom feed
        imagesdir: http://graphitefriction.github.io/writeadapt-graphitefriction/images
    deploy:
      host: github_pages
      branch: gh-pages
